name: Setup AWS Resources

on:
  workflow_dispatch:
    inputs:
      terraform_bucket:
        description: 'S3 bucket name for Terraform state'
        required: true
        type: string
      aws_region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
        type: string

jobs:
  setup:
    name: Create S3 Bucket
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws_region }}
    
    - name: Create S3 bucket
      run: |
        if ! aws s3 ls "s3://${{ inputs.terraform_bucket }}" 2>/dev/null; then
          aws s3 mb s3://${{ inputs.terraform_bucket }} --region ${{ inputs.aws_region }}
          aws s3api put-bucket-versioning --bucket ${{ inputs.terraform_bucket }} --versioning-configuration Status=Enabled
          aws s3api put-bucket-encryption --bucket ${{ inputs.terraform_bucket }} --server-side-encryption-configuration '{
            "Rules": [
              {
                "ApplyServerSideEncryptionByDefault": {
                  "SSEAlgorithm": "AES256"
                }
              }
            ]
          }'
          echo "✅ S3 bucket created: ${{ inputs.terraform_bucket }}"
        else
          echo "✅ S3 bucket already exists: ${{ inputs.terraform_bucket }}"
        fi
